
apiVersion: v1
appVersion: "1.0.1"
version: 1.0.1
kubeVersion: ">=1.11.0-0"
name: helm-operator
description: Flux Helm Operator is a CRD controller for declarative helming
home: https://fluxcd.io
sources:
- https://github.com/fluxcd/helm-operator

dependencies:
- name: helm-operator
  version: 1.0.1
  repository: https://charts.fluxcd.io
